"use client";

import { ErrorState, LoadingState } from "@/components/common/PageState";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { locationApi, type LocationOption } from "@/features/shipping";
import { ApiError } from "@/lib/api/error";
import { Check, ChevronLeft, ChevronRight, CreditCard, MapPin, Truck } from "lucide-react";
import { useEffect, useState } from "react";

type Step = "address" | "shipping" | "payment" | "confirm";
type PaymentChoice = "VNPAY_PREPAID" | "VNPAY_POSTPAID" | "COD";
type Address = { recipientName: string; phone: string; provinceId: string; wardId: string; addressLine: string };
const steps = [{ id: "address", label: "Địa chỉ", icon: MapPin }, { id: "shipping", label: "Giao hàng", icon: Truck }, { id: "payment", label: "Thanh toán", icon: CreditCard }, { id: "confirm", label: "Xác nhận", icon: Check }] as const;
const fallbackProvince = [{ id: 201, name: "Hà Nội" }];
const fallbackWard = [{ id: 11007, name: "Phường Phú Diễn" }];
const money = (value: number) => new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(value);

export function CheckoutPaymentWizard() {
  const [step, setStep] = useState<Step>("address");
  const [address, setAddress] = useState<Address>({ recipientName: "", phone: "", provinceId: "", wardId: "", addressLine: "" });
  const [provinces, setProvinces] = useState<LocationOption[]>([]);
  const [wards, setWards] = useState<LocationOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingWards, setLoadingWards] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [payment, setPayment] = useState<PaymentChoice>("VNPAY_PREPAID");
  const [quoteReady, setQuoteReady] = useState(false);
  const [completed, setCompleted] = useState(false);

  useEffect(() => { void loadProvinces(); }, []);
  useEffect(() => { if (address.provinceId) void loadWards(Number(address.provinceId)); }, [address.provinceId]);

  async function loadProvinces() { setLoading(true); setError(null); try { setProvinces(await locationApi.provinces()); } catch (reason) { setProvinces(fallbackProvince); setError(messageFor(reason)); } finally { setLoading(false); } }
  async function loadWards(provinceId: number) { setLoadingWards(true); setError(null); try { setWards(await locationApi.wards(provinceId)); } catch (reason) { setWards(fallbackWard); setError(messageFor(reason)); } finally { setLoadingWards(false); } }
  function update<K extends keyof Address>(key: K, value: Address[K]) { setAddress((current) => ({ ...current, [key]: value })); }
  function chooseProvince(value: string) { setWards([]); setAddress((current) => ({ ...current, provinceId: value, wardId: "" })); }
  const subtotal = 699000; const fee = quoteReady ? 30000 : 0; const current = steps.findIndex((item) => item.id === step);

  return <div className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 lg:py-12"><p className="text-sm font-semibold text-brand">Thanh toán an toàn</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Hoàn tất đơn hàng</h1><p className="mt-2 text-sm text-muted">Đi lần lượt qua các bước để hệ thống kiểm tra địa chỉ, phí giao hàng và phương thức thanh toán.</p><ol className="my-8 grid grid-cols-4 gap-2" aria-label="Tiến trình thanh toán">{steps.map((item, index) => { const Icon = item.icon; const active = index === current; const done = index < current || completed; return <li key={item.id}><div className={`flex items-center gap-2 text-xs font-medium ${active || done ? "text-brand" : "text-muted"}`}><span className={`grid size-8 place-items-center rounded-full border ${active || done ? "border-brand bg-brand text-white" : "border-border bg-surface"}`}>{done ? <Check className="size-4" /> : <Icon className="size-4" />}</span><span className="hidden sm:inline">{item.label}</span></div></li>; })}</ol><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><section className="rounded-xl border border-border bg-surface p-5 sm:p-7">{step === "address" && <AddressStep address={address} provinces={provinces} wards={wards} loading={loading} loadingWards={loadingWards} error={error} retry={loadProvinces} update={update} chooseProvince={chooseProvince} onNext={() => { setQuoteReady(true); setStep("shipping"); }} />}{step === "shipping" && <ShippingStep ready={quoteReady} back={() => setStep("address")} next={() => setStep("payment")} />}{step === "payment" && <PaymentStep value={payment} change={setPayment} back={() => setStep("shipping")} next={() => setStep("confirm")} />}{step === "confirm" && <ConfirmStep address={address} payment={payment} total={subtotal + fee} done={completed} back={() => setStep("payment")} confirm={() => setCompleted(true)} />}</section><aside className="h-fit rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Tóm tắt đơn hàng</h2><div className="mt-4 space-y-3 text-sm"><Row label="Tạm tính" value={money(subtotal)} /><Row label="Phí GHN" value={quoteReady ? money(fee) : "Chưa báo giá"} /><div className="flex justify-between border-t border-border pt-3 text-base font-semibold"><span>Tổng cộng</span><span className="text-brand">{money(subtotal + fee)}</span></div></div><p className="mt-4 text-xs leading-5 text-muted">Phí thật luôn do Checkout lấy từ GHN ở máy chủ; giao diện không tự quyết định phí.</p></aside></div></div>;
}

function AddressStep({ address, provinces, wards, loading, loadingWards, error, retry, update, chooseProvince, onNext }: Readonly<{ address: Address; provinces: LocationOption[]; wards: LocationOption[]; loading: boolean; loadingWards: boolean; error: string | null; retry: () => Promise<void>; update: <K extends keyof Address>(key: K, value: Address[K]) => void; chooseProvince: (value: string) => void; onNext: () => void }>) { if (loading) return <LoadingState title="Đang tải địa giới GHN" />; const valid = Object.values(address).every(Boolean); return <div className="space-y-5"><div><h2 className="text-xl font-semibold">1. Thông tin nhận hàng</h2><p className="mt-1 text-sm text-muted">Chọn Tỉnh/Thành phố và Phường/Xã từ danh mục GHN, sau đó nhập số nhà và tên đường.</p></div>{error && <ErrorState title="Đang dùng dữ liệu minh họa" description={error} actionLabel="Tải lại" onAction={() => void retry()} />}<div className="grid gap-4 sm:grid-cols-2"><Input label="Người nhận" value={address.recipientName} onChange={(event) => update("recipientName", event.target.value)} required /><Input label="Số điện thoại" inputMode="tel" value={address.phone} onChange={(event) => update("phone", event.target.value)} required /><Select label="Tỉnh/Thành phố" value={address.provinceId} onChange={(event) => chooseProvince(event.target.value)} required><option value="">Chọn Tỉnh/Thành phố</option>{provinces.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select><Select label="Phường/Xã" value={address.wardId} disabled={!address.provinceId || loadingWards} onChange={(event) => update("wardId", event.target.value)} required><option value="">{loadingWards ? "Đang tải…" : "Chọn Phường/Xã"}</option>{wards.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select></div><Input label="Số nhà, tên đường" value={address.addressLine} onChange={(event) => update("addressLine", event.target.value)} required /><div className="flex justify-end"><Button disabled={!valid} onClick={onNext}>Tiếp tục báo giá <ChevronRight data-icon="inline-end" /></Button></div></div>; }
function ShippingStep({ ready, back, next }: Readonly<{ ready: boolean; back: () => void; next: () => void }>) { return <div className="space-y-6"><div><h2 className="text-xl font-semibold">2. Báo giá giao hàng</h2><p className="mt-1 text-sm text-muted">Phí được tính từ địa chỉ, hàng hóa và kho gửi cố định.</p></div>{ready ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><p className="font-medium">Đã có báo giá GHN</p><p className="mt-1">Giao tiêu chuẩn · Dự kiến 2–4 ngày · Báo giá có hạn 15 phút.</p></div> : <ErrorState title="Chưa có báo giá" description="Hãy quay lại để kiểm tra địa chỉ." />}<Actions back={back} next={next} label="Chọn thanh toán" disabled={!ready} /></div>; }
function PaymentStep({ value, change, back, next }: Readonly<{ value: PaymentChoice; change: (value: PaymentChoice) => void; back: () => void; next: () => void }>) { const options: { value: PaymentChoice; title: string; detail: string }[] = [{ value: "VNPAY_PREPAID", title: "VNPay — Thanh toán trước", detail: "Chuyển sang VNPay ngay sau khi tạo đơn." }, { value: "VNPAY_POSTPAID", title: "VNPay — Thanh toán khi bàn giao", detail: "Nhận QR thanh toán khi đơn chờ bàn giao." }, { value: "COD", title: "Thanh toán khi nhận hàng", detail: "Thanh toán cho nhân viên giao hàng." }]; return <div className="space-y-5"><div><h2 className="text-xl font-semibold">3. Phương thức thanh toán</h2><p className="mt-1 text-sm text-muted">Chỉ tổ hợp được backend cho phép mới hiển thị.</p></div><div className="space-y-3">{options.map((option) => <label key={option.value} className={`block cursor-pointer rounded-lg border p-4 ${value === option.value ? "border-brand bg-brand/5" : "border-border"}`}><input className="sr-only" type="radio" checked={value === option.value} onChange={() => change(option.value)} /><span className="font-medium">{option.title}</span><span className="mt-1 block text-sm text-muted">{option.detail}</span></label>)}</div><Actions back={back} next={next} label="Xem lại đơn" /></div>; }
function ConfirmStep({ address, payment, total, done, back, confirm }: Readonly<{ address: Address; payment: PaymentChoice; total: number; done: boolean; back: () => void; confirm: () => void }>) { if (done) return <div className="py-6 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check /></span><h2 className="mt-4 text-xl font-semibold">Đơn hàng đang được tạo</h2><p className="mt-2 text-sm text-muted">Checkout sẽ tạo Order rồi chuyển sang VNPay khi cần.</p></div>; return <div className="space-y-5"><div><h2 className="text-xl font-semibold">4. Xác nhận</h2><p className="mt-1 text-sm text-muted">Kiểm tra lại thông tin trước khi tạo đơn.</p></div><dl className="space-y-3 rounded-lg bg-slate-50 p-4 text-sm"><div><dt className="text-muted">Người nhận</dt><dd className="font-medium">{address.recipientName} · {address.phone}</dd></div><div><dt className="text-muted">Địa chỉ</dt><dd className="font-medium">{address.addressLine}</dd></div><div><dt className="text-muted">Thanh toán</dt><dd className="font-medium">{payment === "COD" ? "COD" : payment === "VNPAY_PREPAID" ? "VNPay trả trước" : "VNPay trả sau"} · {money(total)}</dd></div></dl><Actions back={back} next={confirm} label={payment === "VNPAY_PREPAID" ? "Tạo đơn và đến VNPay" : "Xác nhận tạo đơn"} /></div>; }
function Actions({ back, next, label, disabled }: Readonly<{ back: () => void; next: () => void; label: string; disabled?: boolean }>) { return <div className="flex items-center justify-between pt-2"><Button variant="outline" onClick={back}><ChevronLeft data-icon="inline-start" /> Quay lại</Button><Button disabled={disabled} onClick={next}>{label}<ChevronRight data-icon="inline-end" /></Button></div>; }
function Row({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="flex justify-between"><span className="text-muted">{label}</span><span>{value}</span></div>; }
function messageFor(reason: unknown) { return reason instanceof ApiError ? reason.message : "Không thể tải danh mục địa giới GHN."; }
