spring:
  config:
    import: "optional:file:./.env[.properties],optional:file:./catalog-service/.env[.properties],optional:file:./services/catalog-service/.env[.properties]"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/catalog_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false

server:
  port: ${SERVER_PORT:8082}

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:dynamicmart-identity-service}
      hmac-secret-base64: ${JWT_HMAC_SECRET_BASE64:}
  internal:
    api-key: ${INTERNAL_API_KEY:}
